Feature/crud for label
KurnosovaElena/Management_System pull request #20
Opened 2024-11-20 09:13 UTC by KurnosovaElena

2024-11-20 13:19 UTC, DmitriyG0r4anin reviewed
Are you planning to add pagination later or not?
It would be better to add it now

2024-11-20 13:19 UTC, DmitriyG0r4anin commented on Management_System/DAL/Repositories/Implementations/LabelRepository.cs
> +    }
You can use => instead of curly braces (for better look)

2024-11-20 13:19 UTC, DmitriyG0r4anin commented on Management_System/Management_System/Controllers/LabelController.cs
> +    public async Task<LabelEntity> Add(LabelEntity entity, CancellationToken cancellationToken)
Better to add [FromBody] to LabelEntity

2024-11-20 13:19 UTC, DmitriyG0r4anin commented on Management_System/Management_System/Controllers/LabelController.cs
> +    public async Task<LabelEntity> Update(Guid id, LabelEntity entity, CancellationToken cancellationToken)
same to previous

2024-11-20 13:19 UTC, DmitriyG0r4anin commented on Management_System/Management_System/Controllers/LabelController.cs
> +    public async Task Delete(Guid id, CancellationToken cancellationToken)
same to previous

2024-11-20 17:51 UTC, Gh0stF1ghter requested changes

2024-11-20 17:51 UTC, Gh0stF1ghter commented on Management_System/Management_System/Controllers/BoardController.cs
> +    public async Task<BoardEntity> Update([FromBody] Guid id, BoardEntity entity, CancellationToken cancellationToken)
Are you sure you're getting id from the body?

2024-11-20 17:51 UTC, Gh0stF1ghter commented on Management_System/Management_System/Controllers/BoardController.cs
> +    public async Task Delete([FromBody] Guid id, CancellationToken cancellationToken)
Same

2024-11-20 17:51 UTC, Gh0stF1ghter commented on Management_System/Management_System/Controllers/LabelController.cs
> +    public async Task<LabelEntity> Update([FromBody] Guid id, LabelEntity entity, CancellationToken cancellationToken)
Same

2024-11-20 20:10 UTC, Gh0stF1ghter approved these changes

2024-11-21 12:45 UTC, VladPristavkin approved these changes

2024-11-21 13:20 UTC, merged