Feature/add entities
KurnosovaElena/Management_System pull request #9
Opened 2024-10-28 12:35 UTC by KurnosovaElena

2024-10-28 12:39 UTC, nantonov requested changes

2024-10-28 12:39 UTC, nantonov commented on Management_System/Management_System/Entities/Board.cs
> +        public IEnumerable<Table>? Tables { get; set; }
instead of nullabel use `= [];` by default for all collecions in entities

2024-10-28 12:39 UTC, nantonov commented on Management_System/Management_System/Enums/TaskEstimation.cs
> +    public enum TaskEstimation
let's use default values for all enums
https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/enum

2024-10-28 12:46 UTC, 5Ka-me commented on Management_System/Management_System/Entities/Label.cs
> +        public int Guid { get; set; }
What is it?

2024-10-28 15:02 UTC, Gh0stF1ghter approved these changes

2024-10-28 15:02 UTC, DmitriyG0r4anin commented on Management_System/Management_System/Entities/Label.cs
> +        public int Guid { get; set; }
+

2024-10-28 15:05 UTC, 5Ka-me requested changes

2024-10-28 15:05 UTC, 5Ka-me commented on Management_System/Management_System/Entities/Board.cs
> +﻿namespace Management_System.Entities
Isn't namespace should be the same as in others files?

2024-10-28 15:05 UTC, 5Ka-me commented on Management_System/Management_System/Entities/Task.cs
> +    public class Task
I was thinking about name of this class. We already have class `Task` in the .Net.

2024-10-29 01:08 UTC, 5Ka-me commented on Management_System/Management_System/Entities/User.cs
> +
Why there are two blank lines?

2024-10-29 01:09 UTC, 5Ka-me approved these changes

2024-10-29 08:54 UTC, nantonov approved these changes

2024-10-29 08:57 UTC, merged